---
settings:
  name: EDA workloads
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: EDA 워크로드 문서
    url: "/index.html"
  - title: 릴리스 노트
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 알려진 제한 사항
      url: "/known-limitations.html"
  - title: 시작하기
    entries:
    - title: NetApp Workload Factory for EDA에 대해 알아보세요.
      url: "/learn-eda.html"
    - title: 빠른 시작
      url: "/quick-start-eda.html"
  - title: 프로젝트 대시보드를 사용하세요
    entries:
    - title: 대시보드를 사용하세요
      url: "/task-configure-dashboard.html"
  - title: 볼륨 지연 시간 모니터링
    entries:
    - title: 볼륨 지연 시간 모니터링
      url: "/task-monitor-latency.html"
  - title: Perforce 통합 기능을 사용하세요.
    entries:
    - title: Perforce 통합에 대해 알아보세요.
      url: "/learn-eda-workloads.html"
    - title: 요구 사항
      url: "/requirements-eda.html"
    - title: 프로젝트 관리
      url: "/manage-projects.html"
    - title: 프로젝트 버전 관리
      url: "/version-projects.html"
    - title: 워크스페이스 만들기
      url: "/create-workspaces.html"
    - title: Codebox로 자동화하세요
      url: "/automate-codebox.html"
    - title: Perforce와 통합
      url: "/integrate-perforce.html"
  - title: 지식과 지원
    entries:
    - title: 지원 등록
      url: "/support-registration.html"
    - title: 도움을 받으세요
      url: "/get-help-eda.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
