---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, Workload Factory, builders, Workload Factory, EDA, electronic design automation' 
summary: EDA용 Workload Factory의 새로운 기능을 알아보세요. 
---
= NetApp Workload Factory for EDA의 새로운 기능은 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory의 EDA 기능에 새로 추가된 기능을 알아보세요.



== 2026년 1월 4일



=== NetApp Workload Factory for Builders가 이제 NetApp Workload Factory for EDA로 변경되었습니다.

Workload Factory for Builders가 이제 Workload Factory for EDA로 이름이 변경되었습니다. 이번 명칭 변경은 전자 설계 자동화(EDA) 워크로드에 대한 집중을 반영합니다.

Workload Factory for EDA는 여러 파일 시스템에서 ONTAP 용 FSx를 최적화하는 데 도움을 줍니다. 스토리지 매개변수를 자동화하고, 성능 제약 조건을 분석하고, EDA 프로젝트에 대한 통찰력을 얻음으로써 성능을 최적화하고 운영 비용을 절감할 수 있습니다. EDA용 워크로드 팩토리는 IaC(Infrastructure as Code) 프레임워크와 통합되도록 설계되었습니다.



=== Ask me AI 어시스턴트 홈페이지 통합

Workload Factory 콘솔 홈 페이지에는 Ask me AI 어시스턴트가 내장되어 있어 스토리지 환경에 대한 질문을 하고, 환경에서 직접 맞춤형 인사이트를 얻고, 이전 대화를 참조할 수 있습니다. Ask me 기능을 사용하면 콘솔을 벗어나지 않고도 워크로드를 이해하고, 문제를 해결하고, Workload Factory에 대해 자세히 알아볼 수 있습니다.



== 2025년 10월 5일



=== BlueXP workload factory NetApp Workload Factory 변경되었습니다.

BlueXP 데이터 인프라 관리에 있어서의 역할을 더 잘 반영하도록 이름이 바뀌고 재설계되었습니다. 결과적으로 BlueXP workload factory NetApp Workload Factory 로 이름이 변경되었습니다.



== 2025년 6월 16일



=== 클론 지원

이제 BlueXP Workload Factory for Builders에서 프로젝트를 복제할 수 있습니다. 프로젝트를 복제하면 Builders는 스냅샷에서 원본과 동일한 구성의 새 프로젝트를 생성합니다. 클론 기능은 유사한 프로젝트를 빠르게 생성하거나 테스트 목적으로 사용할 때 유용합니다. Builders의 지침에 따라 새 프로젝트 복제본을 마운트할 수 있습니다.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["BlueXP Workload Factory for Builder 프로젝트의 버전을 관리합니다."]



== 2025년 5월 4일



=== 업데이트된 권한 용어

Workload Factory 사용자 인터페이스 및 문서에서는 이제 읽기 권한을 나타낼 때 "읽기 전용"이라는 용어를, 자동화 권한을 나타낼 때 "읽기/쓰기"라는 용어를 사용합니다.



== 2024년 12월 1일



=== 빌더 워크로드 초기 릴리스

BlueXP Workload Factory for Builders는 소프트웨어 버전 사용 및 접근을 간소화하여 맞춤형 도구나 스크립트가 필요하지 않도록 해줍니다. 이 기능을 통해 Perforce Helix Core와 통합된 편리한 개발 작업 공간으로 소프트웨어 버전을 즉시 복제하여 사용할 수 있으므로 시간과 리소스를 절약할 수 있습니다.

초기 릴리스에는 Codebox를 사용하여 프로젝트 및 작업 공간을 관리하고 작업을 자동화하는 기능이 포함되어 있습니다. 빌더를 Perforce Helix Core와 통합하면 각 프로젝트의 다양한 버전을 관리하고 빠르게 전환할 수 있습니다.
